### ISSUE TITLE
The PROGRAM VIDEOS and PC2's HOUSING PROGRAM pages don't change the nav-bar

### ISSUE THREAD

**Issue by MistySunMew** [SpeakingInBits/PC2#206]
When accessing the PROGRAM VIDEOS and PC2's HOUSING PROGRAM pages the nav-bar does not update to show what page you are on properly

**Comment by JoeProgrammer88** [comment]
![image](https://user-images.githubusercontent.com/7156063/221002629-c55c67a6-190d-447f-b7c8-ca2fb33ad51a.png)

When the user is on a specific page, the corresponding link in the navigation should have black font

**Comment by MistySunMew** [comment]
![image](https://user-images.githubusercontent.com/106198772/221002841-54a253c5-c42c-4915-b569-2f039ea24a29.png)
What it currently looks like when on the program videos page

**Comment by MistySunMew** [comment]
With further testing these pages don't trigger the code to say they are the active page

Home:

![image](https://user-images.githubusercontent.com/106198772/221006589-78bb888c-1594-4c0e-a02c-5b5fade0e8ad.png)

Program videos:

![image](https://user-images.githubusercontent.com/106198772/221006654-5c24052f-bd7a-439f-8950-49e5f193b30b.png)
