### ISSUE TITLE
Mobile navigation bug

### ISSUE THREAD

**Issue by JoeProgrammer88** [SpeakingInBits/PC2#222]
![image](https://user-images.githubusercontent.com/7156063/224117322-9f705a8b-956f-4895-9ea3-40807dde550b.png)

When on a mobile sized device, clicking one of the dropdown menus, blurs the menus together (see screenshot). A non pop out menu for the dropdowns might be a potential fix

The users need to see the navigation items clearly and be able to click them easily

**Comment by sk8kitty** [comment]
I'll take this issue!
