### ISSUE TITLE
Documentation for Models

### ISSUE THREAD

**Issue by JoeProgrammer88** [SpeakingInBits/PC2#234]
These classes are lacking in documentation. The class itself, any methods, and properties need documentation
- [x] #233 
- [x] #235
- [x] #236
- [x] #237
- [x] #238
- [x] #239
- [x] #240
- [x] #241

**Comment by ScottProgrammer88** [comment]
Moved Board class to People.cs and added documentation.

**Comment by JoeProgrammer88** [comment]
All subtasks have been completed
