### ISSUE TITLE
Document ContactPageModel

### ISSUE THREAD

**Issue by JoeProgrammer88** [SpeakingInBits/PC2#237]

**Comment by crex424** [comment]
@JoeProgrammer88 For the Name field, is it the Contacts full name? If it wants the full name, then what format is it in:
"Last name, First name" or "First name Last name"?

**Comment by JoeProgrammer88** [comment]
@crex424 The client does not currently have requirements for the display name. Right now it's just their preferred name to be called. It could be just a first name, or a first and last combination, or even multiple words at the moment

**Comment by JoeProgrammer88** [comment]
Merged in #249
