### ISSUE TITLE
Document NewsletterFile model

### ISSUE THREAD

**Issue by JoeProgrammer88** [SpeakingInBits/PC2#238]

**Comment by crex424** [comment]
@JoeProgrammer88 What is the purpose of this class. Is it to store and display Newsletters? Please and thank you.

**Comment by JoeProgrammer88** [comment]
@crex424 That is correct. If you look in the AboutController where the NewsletterFile is referenced, the Name is the file name of the NewsletterFile as it is saved on the disk. The location is the relative path where it is stored on the web server. The NewsletterId is the typical primary key field to uniquely identify each newsletter.
