### ISSUE TITLE
Add QR Code image for authenticator app

### ISSUE THREAD

**Issue by JoeProgrammer88** [SpeakingInBits/PC2#265]
To make it easier for the client to add 2FA to their account, the Two-factor authentication page should have a scannable QR code image.
https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes?view=aspnetcore-7.0

This page is found on the website by logging into the admin account, clicking on the `Hello admin...` greeting, and going to the Two-factor authentication page

**Comment by wrecknralph** [comment]
I will take this issue.

**Comment by JoeProgrammer88** [comment]
Closed in #286
