### ISSUE TITLE
Events Calendar Display

### ISSUE THREAD

**Issue by JoeProgrammer88** [SpeakingInBits/PC2#317]
Client would like the Events calendar to be displayed as a calendar instead of a list. When clicking on a cell, the event link or an RSVP would pop up

![image003](https://github.com/SpeakingInBits/PC2/assets/7156063/5b56385f-6a20-42ad-b2b2-cca7c668816e)

**Comment by cameronwhite4121** [comment]
How are calendar events added into the db?

**Comment by cameronwhite4121** [comment]
[FullCalendar Repo](https://github.com/fullcalendar/fullcalendar/tree/main?tab=readme-ov-file) - Link leads to popular calendar api with documentation links.
[Bootstrap Modals](https://getbootstrap.com/docs/5.3/components/modal/#exampleModalPopovers) - Styling for popup modals

**Comment by JoeProgrammer88** [comment]
> How are calendar events added into the db?

@cameronwhite4121 In the `CalendarController.Create` method. You must be logged in as an admin to get to the pages within the controller

**Comment by cameronwhite4121** [comment]
Thanks, I temporarily removed the check for admin so I could ensure create page was still functional. I created test data locally to make sure the calendar is functional, and it seems like its working as intended. Switching between PC2 calendar events and County-wide events works as well. Gonna do a pull request for code review.
